//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamKanaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMarket
    {
        public int ID { get; set; }
        public string Ttitle { get; set; }
        public string Genre { get; set; }
        public string Author { get; set; }
        public double Cost { get; set; }
        public int CountInShop { get; set; }
        public int CoutInStock { get; set; }
        public string Desciption { get; set; }
        public string Image { get; set; }
    }
}
